name: Build and deploy site to AWS S3 bucket

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - run: "npm install"
            - run: "npm run build"
            - name: configure aws credentials
              uses: aws-actions/configure-aws-credentials@v1.7.0
              with:
                  role-to-assume: ${{ secrets.AWS_IDENTITY }}
                  role-session-name: GitHub_to_AWS_via_FederatedOIDC
                  aws-region: ${{ secrets.AWS_REGION }}
            - name: Sts GetCallerIdentity
              run: |
                  aws sts get-caller-identity
